### ISSUE TITLE
Ошибка  Return value must be of type yii\web\IdentityInterface, null returned

### ISSUE THREAD

**Issue by hacan359** [cusodede/yii2-permissions#10]
Ошибки в случае если не авторизованный пользователь попадает в контроллер с подключенным PermissionFilter MaAMoiseev A minute ago
cusodede\permissions\PermissionsModule::UserCurrentIdentity(): Return value must be of type yii\web\IdentityInterface, null returned

**Comment by pozitronik** [comment]
fixed at #13
