### ISSUE TITLE
Не добавляются разрешения для модулей

### ISSUE THREAD

**Issue by s1lver** [cusodede/yii2-permissions#28]
Если в конфиг добавить пути на модули, например так

```php
[
    'controllerDirs' => [
        '@app/modules/api/controllers' => '@api',
        '@modules/import/controllers' => '@import',
    ]
]
```
и вызвать команду

```bash
php yii permissions/default/init-controllers-permissions
```

то получим ошибку
```
Exception 'pozitronik\relations\models\RelationException' with message 'Relation save error.'

in /var/www/vendor/pozitronik/yii2-relations/src/traits/RelationsTrait.php:153
```

**Comment by pozitronik** [comment]
Не учитывается наличие кеша => добавить в тесты прохождение с включённым кешем.

**Comment by pozitronik** [comment]
Судя по описанию симптомов, модуль пытается строить какие-то связи по данным из кеша. Решением может быть сброс кешей перед вызовом генератора, но лучше разобраться, какие именно данные используются.

**Comment by pozitronik** [comment]
Саморассос, если повторится - разберёмся.
