### ISSUE TITLE
Утечка памяти

### ISSUE THREAD

**Issue by antonshevelev** [cusodede/yii2-permissions#57]
Причина учетки PermissionsModule::GetControllersList, котрый вызывается в GridView.
Кол-вы вызовов равно ко-ву строк в таблице. 
Каждый вызов PermissionsModule::GetControllersList может отведать приличное кол-во памяти.

**Comment by pozitronik** [comment]
Фактически это происходит из-за того, что в конструкторах некоторых контроллеров есть всякие другие вызовы. Это легитимно, конечно.
Попробую переписать так, чтобы сбор данных по контроллерам, нужный во вьюхе, производился без их загрузки, либо совсем не производился.
